version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: appbanque_php
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=pgdbbanque
      - DB_USERNAME=pguserbanque
      - DB_PASSWORD=pgpassword
    volumes:
      - .:/var/www/html
    networks:
      - backend
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: appbanque_nginx
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  postgres:
    container_name: postgresbanque
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: pgdbbanque
      POSTGRES_USER: pguserbanque
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer:latest
    container_name: adminerbanque
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend: